# formatting notes:
# this is a comment.  copy this file, call it 'main.conf' and add your config key/value pairs in the format below.
# (delete this initial section; useful keys start in the "database connection info" section, below.)
some_key = some_value
another_key = "a value that contains quotes.  (all config values are strings until you use api.util.config.set_config_value to add value of a different type.)"
yet another valid key = ignore any warnings from whatever IDE you're using;  this will work.  having said that, here's an extra apostrophe so that it won't think this is all a string: '

# database connection info:
db_host = localhost

db_user = audioid_user
db_user_password = fill in an actual value.

db_music_admin = audioid_music_admin
db_music_admin_password = fill in an actual value.

db_user_admin = audioid_user_admin
db_user_admin_password = fill in an actual value.

db_name = audioid
db_charset = utf8